### ISSUE TITLE
Why there's no sourcecode in Video 5.4 folder?

### ISSUE THREAD

**Issue by tennessine** [PacktPublishing/Building-Recommendation-Systems-with-Python#3]

**Comment by tennessine** [comment]
@siddheshkavle

**Comment by ericandrer** [comment]
Hi @tennessine thanks for pointing out the missing sourcecode. It has been uploaded [https://github.com/PacktPublishing/Building-Recommendation-Systems-with-Python/pull/2](#2)

**Comment by ericandrer** [comment]
Hi @tennessine thanks for letting us know about the missing files. It has been uploaded here [#2](https://github.com/PacktPublishing/Building-Recommendation-Systems-with-Python/pull/2).
