### ISSUE TITLE
CSV files

### ISSUE THREAD

**Issue by Tharnid** [PacktPublishing/Building-Recommendation-Systems-with-Python#5]
Hello.

Where are the csv files for this course?  I am looking specifically for the IMDB database in section 2.  Let me know.

Thanks.

Tharnid

**Comment by delmico** [comment]
Same here, I cannot find the .csv files for this course. For instance, in section 2, the 'movies_metadata.csv' file is missing. See screenshot
![Capture](https://user-images.githubusercontent.com/11274128/82271099-b787df80-992b-11ea-9241-448fba65cd69.PNG)

**Comment by ericandrer** [comment]
Hi @Tharnid @perledeau  please find the files on [G Drive](https://drive.google.com/drive/folders/13sgsgTDV_XmtZnAI1xcdLEAVzLUeVcZ7?usp=sharing) there weren't uploaded on Github due to size restrictions. [Learn more](https://docs.github.com/en/github/managing-large-files/what-is-my-disk-quota)
